### ISSUE TITLE
More feature

### ISSUE THREAD

**Issue by BioBut** [rubanero14/RSS-Feed-CP-Prototype#1]
Example:
https://github.com/putuwahyu29/feednews

**Comment by rubanero14** [comment]
> Example:
> https://github.com/putuwahyu29/feednews

Interesting. What more features needed?

**Comment by BioBut** [comment]
Other Example
https://github.com/shankrmahadevan/tamil-news-feed

**Comment by rubanero14** [comment]
> Other Example
> https://github.com/shankrmahadevan/tamil-news-feed

Demo?

**Comment by BioBut** [comment]
No but Look like news Website.

**Comment by rubanero14** [comment]
Sorry what are you trying to imply here?, And what features are missing?

**Comment by BioBut** [comment]
> Sorry what are you trying to imply here?

https://github.com/shankrmahadevan/tamil-news-feed
Currently not available demo but i check this website source code .
This website Use RSS  Feed But Look like News Website

**Comment by rubanero14** [comment]
> > Sorry what are you trying to imply here?
> 
> https://github.com/shankrmahadevan/tamil-news-feed
> 
> This website Use RSS  Feed But Look like News Website

I cant see the website, so hard to comment on it. About this repo is a multi sources scalable RSS feed plugin/component, not meant for making a news website, it is meant for easily integrated into Vue projects that requires custom RSS scalable feed. I did this as tech demo for client who needs a reusable plugin RSS reader plugin. For a news website, I have plans too and I'll keep in mind doing a full news website. Don't mind suggesting what features needed based on your view for news website? Thanks

**Comment by BioBut** [comment]
Okay Thanks

**Comment by rubanero14** [comment]
> > Sorry what are you trying to imply here?
> 
> https://github.com/shankrmahadevan/tamil-news-feed
> Currently not available demo but i check this website source code .
> This website Use RSS  Feed But Look like News Website

It would be nice if this author set up his GitHub Pages for this repo

**Comment by rubanero14** [comment]
> Okay Thanks

Thank you for the suggestions

**Comment by rubanero14** [comment]
@BioBut Review the site now, features added as per your suggestion

**Comment by BioBut** [comment]
> @BioBut Review the site now, features added as per your suggestion

nice features but other example

**Comment by rubanero14** [comment]
> > @BioBut Review the site now, features added as per your suggestion
> 
> nice features but other example
> 
>  https://www.zergnet.com/

Nice site. Will look it up a way

**Comment by BioBut** [comment]
More Rss Feed Link available


https://github.com/simevidas/web-dev-feeds

**Comment by rubanero14** [comment]
> More Rss Feed Link available
> 
> 
> https://github.com/simevidas/web-dev-feeds

Interesting repo. Nice place to hunt for more sources. Thanks again. What do you think about this?
https://github.com/impressivewebs/frontend-feeds

**Comment by rubanero14** [comment]
> More Rss Feed Link available
> 
> https://github.com/simevidas/web-dev-feeds

More sources of RSS links added as per request

**Comment by BioBut** [comment]
Nice Project But Your project not support  1000 Rss Feed But possible 
example:
https://github.com/MillanUka/RSS-Feed-Reader

**Comment by rubanero14** [comment]
I have reviewed her website, looks like she uses dynamic RSS feed url inputs from user itself and store them in to their local storage. There is another issue, since all XML are unique in structure, might break or can't support by her application. Unless she handled different possible type of XML structure, that's good. Nice feature btw. But maybe I can do this for my own project in future in separate project, easy one. The issue is for this component, since my client only wants selected feeds into his components, bear in mind this is for Fintech website of his. So that's the limitation. Otherwise awesome suggestion. Technically, this component can support unlimited amount of feeds and topics, but it's hard coded and not user specific like u suggested. Thanks again for the input.
