### ISSUE TITLE
NFL News

### ISSUE THREAD

**Issue by serendrewpity** [rubanero14/RSS-Feed-CP-Prototype#2]
Would like to be able to have an RSS Feed for NFL News (www.nfl.com/news).

**Comment by rubanero14** [comment]
> Would like to be able to have an RSS Feed for NFL News (www.nfl.com/news).

@serendrewpity Sure thing, will add this into the next release

**Comment by rubanero14** [comment]
> Would like to be able to have an RSS Feed for NFL News (www.nfl.com/news).

[30-06-24] New Feed for NFL added under NFL Updates section. Happy reading
